services:
  php:
    build: images/php/8.3
    container_name: magento_php
    volumes:
      - srcdata:/var/www/html
      - ./src/app:/var/www/html/app
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./src/composer.json:/var/www/html/composer.json
      - ./src/composer.lock:/var/www/html/composer.lock
      #Mounting the vendor will slow down (really slow down) all you do
      #  in your container alternatively you can rsync or cp the
      #  vendor folder in the container after running composer
      #  install/update. Try and see what works for you. The copy cmd:
      #  "docker compose cp php:/var/www/html/vendor/. src/vendor/"
      #- ./src/vendor:/var/www/html/vendor:cached
    working_dir: /var/www/html
    extra_hosts:
      #Without the host.docker.internal set to you workstations IP
      #  the debugger (xdebug) will not work; set the host.docker.internal
      #  in your etc/hosts file to your workstation internal IP
      #  (like 192.168.1.x)
      - "host.docker.internal:host-gateway"
    networks:
      - magento
    dns:
      - 8.8.8.8
    depends_on:
      - mariadb
      - opensearch
      - rabbitmq
      - redis

  nginx:
    image: nginx:latest
    container_name: magento_nginx
    depends_on:
      - php
    volumes:
      - srcdata:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - magento
    ports:
      - "80:80"

  mariadb:
    image: mariadb:10.6
    container_name: magento_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    networks:
      - magento
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: magento_opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    restart: always
    ports:
      - 9200:9200
    networks:
      - magento

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: magento_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magento

  redis:
    image: redis:7.2-alpine
    container_name: magento_redis
    ports:
      - "6379:6379"
    networks:
      - magento

volumes:
  dbdata:
  opensearch-data:
  srcdata:
networks:
  magento:
    name: magento_network
    driver: bridge

